version: '3.8'

services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lifescape
    ports:
      - '5432:5432'

  api:
    build: ./api
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/lifescape
    ports:
      - '4000:3000'
    depends_on:
      - db

  client:
    build: ./client
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  db-data:

